### Récupération de tous les médias (non utilisé pour le front)
GET http://localhost:8080/api/media/all

### Récupération d'une page de médias avec pagination et tri "par défaut"
GET http://localhost:8080/api/media/all/0

### Récupération d'une page de médias triés par date
GET http://localhost:8080/api/media/all/date/0

### Récupération d'une page de médias filtrés par genre
GET http://localhost:8080/api/media/all/genre/Action/0

### Récupération d'une page de films OU séries
GET http://localhost:8080/api/media/all/type/MOVIE/0

### Récupération des détails d'un média par son ID
GET http://localhost:8080/api/media/53be62a6-4d7d-407f-af57-6b93be4abaf7

### Récupération des évaluations pour un média
GET http://localhost:8080/api/evaluation/media/53be62a6-4d7d-407f-af57-6b93be4abaf7/2

### Récupération de tous les genres de médias disponibles
GET http://localhost:8080/api/genre/all

### Recherche par titre
GET http://localhost:8080/api/media/search/les

